nav:
  - 🏡 主页: # 主页/
      - index.md

  - C++:
      - cpp/index.md
      - 复试注意点-553: cpp/553.md
      - 553递归问题: cpp/553递归问题.md
      - c字符数组和cpp字符串之间的转换: cpp/c字符数组和cpp字符串之间的转换.md
      - 读入问题: cpp/读入问题.md
      - C++基础知识:
      
        - 类:
            - 静态数据成员: cpp/base/类/静态数据成员.md
        - 文件操作: 
          - 写入/读出: cpp/base/文件操作/文件操作.md
          - 调整指针位置: cpp/base/文件操作/指针位置调整.md
          
        - 运算符重载:
          - 加号运算符重载: cpp/base/运算符重载/加号运算符重载.md
          - 左移运算符重载: cpp/base/运算符重载/左移运算符重载.md
          - 自增运算符重载: cpp/base/运算符重载/自增运算符重载.md
          - 赋值运算符重载: cpp/base/运算符重载/赋值运算符重载.md
          - 关系运算符重载: cpp/base/运算符重载/关系运算符重载.md
          - 函数运算符重载: cpp/base/运算符重载/函数调用运算符重载.md
          - 加等运算符重载: cpp/base/运算符重载/加等运算符重载.md
        - stl库函数: 
          - stl: cpp/base/stl/stl.md
          - string函数详解: cpp/base/stl/string.md
        - 指针:
          - 函数指针: cpp/base/指针/函数指针.md
          - 数组指针: cpp/base/指针/数组指针.md

      - 常用api: 
        - 整型与字符串的转换: cpp/api/整型与字符串的转换.md
        - 随机数: cpp/api/rand.md
        - 常用api: cpp/api/常用api.md
        - 排序: cpp/api/sort.md

      - c知识:
        - 字符串函数: cpp/c/字符串函数.md
        - 内存移动问题: cpp/c/内存.md

      - 内存分区模型:
        - 分区详情: cpp/内存分区模型/分区详情.md



      - C++零碎杂记:
          - 值类型与右值引用: cpp/零碎杂记/值类型与右值引用.md
      - Effective Modern C++:
          - item1：理解模板类型推导: cpp/effective/item1.md

  - vue:
      - vue/index.md
  - 零碎知识:
      - fragmentKnowledge/index.md
      - 命名规范:
        - 英文单词规范: fragmentKnowledge/命名规范/nameruler.md
        


  - 算法:
      - algorithm/index.md
      - 数学:
        - gcd && lcm: algorithm/数学/gcd&lcm.md
      - 经典算法:
        - 反转链表: algorithm/经典算法/ReverseLinkedList.md
        - 简单排序算法: algorithm/经典算法/简单排序算法.md
        - 数组位置交换: algorithm/经典算法/数组交换位置.md
      - 二叉树:
        - 二叉搜索树:
          - 关于二叉搜索树: algorithm/二叉树/二叉搜索树/关于二叉搜索树.md
        - 前序中序构造树: algorithm/二叉树/前序+中序构造树.md
        - 后序中序构造树: algorithm/二叉树/后序+中序构造树.md
        - 前序后序构造树: algorithm/二叉树/前序+后序构造树.md

  - 生活:
    - life/index.md
    # - 游戏王md:
    #   - life/游戏王md/index.md
    #   - 废二:
    #     - 废二展开: life/游戏王md/废二/废二展开.md

    - 生活作息规划:
      - life/生活作息规划/index.md
      - 时间表: life/生活作息规划/时间表.md


site_name: fmy's notes
site_url: https://fmy-fly.github.io/
repo_name: fmy-fly.github.io
repo_url: https://github.com/fmy-fly/fmy-fly.github.io/

theme:
  name: material
  logo: logo.ico
  favicon: logo.ico
  features:
    - navigation.tabs # 一级导航在横着的导航栏
    - content.code.annotate # 可以在代码块中增添点击展示的注释，参见 https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-annotations
    # - navigation.tracking # 地址栏中的 URL 会随当前位置变化为对应小节的 URL
    - navigation.indexes # 将 index 页面直接附到小节名上
    - navigation.top # 回到顶部按钮
    # - navigation.sections # 二级导航是粗体
    # - navigation.expand # 导航默认展开
    - toc.follow # toc 跟随
    # - toc.integrate # 文档 toc 集成到总目录中
  language: "zh"
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: cyan
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Noto Serif SC # Roboto
    code: Roboto Mono
  custom_dir: overrides

edit_uri: ""

markdown_extensions:
  - toc:
      permalink: true # link for each title
      slugify: !!python/name:pymdownx.slugs.uslugify # enable Unicode link


  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - tables
  - meta
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      # smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets: # 允许将其他文件内容插入文件，语法是 --8<-- "filename.ext" 等，参见 https://facelessuser.github.io/pymdown-extensions/extensions/snippets/#snippets-notation
      auto_append:
        - includes/abbreviations.md
      base_path: ["docs"]
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  analytics:
    provider: google
    property: G-JT9BRCXKJJ
  # social:
  #   - icon: fontawesome/brands/github
  #     link: https://github.com/smd1121
  #   - icon: fontawesome/solid/envelope
  #     link: mailto:xianyuxuan@outlook.com

# extra:
#   search:
#     language: 'jp'
#   pagetime: 'on'

copyright: '本页面的全部内容在 <a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh">CC BY-SA 4.0</a> 和 <a href="https://github.com/zTrix/sata-license">SATA</a> 协议之条款下提供，附加条款亦可能应用'

extra_css:
  - "from_oi_wiki/css/extra.css?v=13"
  - css/status.css
  - css/neoteroi-mkdocs.css

extra_javascript:
  - "from_oi_wiki/js/extra.js"
  - js/mathjax.js # 支持数学公式，ref : https://squidfunk.github.io/mkdocs-material/reference/mathjax
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js # 支持表格排序
  - js/tablesort.js

plugins:
  - search:
      separator: '[\s\u200b\-]'
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - statistics
  - termynal:
      title: ""
      buttons: macos
      prompt_literal_start:
        - "$"
        - ">"
        - "%"
